### ISSUE TITLE
Launching srvdir.exe from Firefox download dialog exposes system32 folder

### ISSUE THREAD

**Issue by cranca** [inconshreveable/srvdir#12] opened 2015-08-12 11:15 UTC
Hi,

I don't know is a feature or a bug... but I prefer to report it.

Reproduce it:
- Download srvdir.exe via Firefox(40)
- Open the download dialog and double click the downloaded item
- Double click the file in the apearing window

![2015-08-12_13-12-11](https://cloud.githubusercontent.com/assets/1257187/9222665/d9b37abe-40f3-11e5-8435-fba68657d501.png)

Note that the file is placed, after download, at its final destination but is executing from \Temp dir as you can see at the screenshot.

**Comment by inconshreveable** [comment] 2016-04-09 01:07
this is an unfortunate side effect of the fact that windows decides to run double-clicked files with the current working directory set to `C:\Windows\system32`. I agree it's definitely not ideal, but not a bug. Closing

**Closed by inconshreveable** 2016-04-09 01:07 UTC
